Clone of the Newsweek page using the framework bootstrap
javierbotero/Newsweek-bootstrap-project pull request #3
Opened 2020-01-31 22:30 UTC by javierbotero

The entire page was build using the different breakpoints of bootstrap and the classes for building the layout. Any feedback would be greatly appreciated.

2020-01-31 22:42 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2020-01-31 23:09 UTC, Anna-Myzukina commented
### Hi team!
### Nice job! WOW, project looks! :+1: 

### But your project needs a few changes before it can be approved.

##### [OPTIONAL] Navigation bar
* Delete space above header
![space](https://user-images.githubusercontent.com/26605804/73580740-52e56980-448f-11ea-8f17-6972942fa368.png)


##### Footer

*  It contains social media icons ([link to page](https://www.newsweek.com/))
In original version you can see social media icons

![icons](https://user-images.githubusercontent.com/26605804/73580390-0fd6c680-448e-11ea-88ac-bc3e28230a90.png)

In your version social icons are absent
![icons2](https://user-images.githubusercontent.com/26605804/73580393-1402e400-448e-11ea-861e-590381827c48.png)

* **Footer should changes with RWD breakpoints** ([link to page](https://www.newsweek.com/))

#### Implementation details


* Kindly recommended to use Bootstrap Css classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) )

![screen](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png)

![screen](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png)
### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

2020-01-31 23:12 UTC, Anna-Myzukina commented on index.html
> +                    </div>
Line number 434: content "In the magazine" should be uppercase, kindly recommended to fix it

2020-01-31 23:13 UTC, Anna-Myzukina requested changes
The project needs changes

2020-02-01 17:14 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

#### Hello @javierbotero :handshake: 

### Amazing job the amount of detail is impressive :medal_sports: there are some changes to make yes but they are all very minor:

**Hamburger menu**

- [x] Add a hamburger menu in the navbar for your small and medium screen sizes

 - Yours 

![image](https://user-images.githubusercontent.com/52209067/73595758-c0ba8100-44e1-11ea-9e01-b756754f053c.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73595777-e21b6d00-44e1-11ea-83b3-8709d932bb12.png)

**Preview magazine**

- [x] Increase the height of the preview magazine in small screens size also the IN THE MAGAZINE title has to come after the preview magazine and not on top

- Yours

![image](https://user-images.githubusercontent.com/52209067/73595859-8e5d5380-44e2-11ea-8ac8-d45ea8086feb.png)


- Original

![image](https://user-images.githubusercontent.com/52209067/73595844-62da6900-44e2-11ea-8f11-6f73a29db10c.png)

**SUBSCRIBE and NEWSLETTER**

- [x] change the SUBSCRIBE and NEWSLETTER titles to have a red font color 

- Yours

![image](https://user-images.githubusercontent.com/52209067/73595914-29eec400-44e3-11ea-9337-bc59a31adfc8.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73595926-3ecb5780-44e3-11ea-8919-07eb7f197804.png)

**Bootstrap usage**

- [x] Your CSS file still have selectors that can be replaced with bootstrap classes, I have left comments where selectors have to be removed.

That's it! :raised_hands:  

### Its been a true blast :guitar:  to review this project, Please :pray:  make the changes and submit back for a code review :rocket: keep up the good work! :muscle: 

Happy coding! :woman_technologist: 

PROJECT_SATUS: REQUESTED CHANGES :stop_sign:

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  text-align: center;
Use [bootstrap classes for text-align](https://getbootstrap.com/docs/4.4/utilities/text/#text-alignment) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  text-align: right;
Use [bootstrap classes for text-align](https://getbootstrap.com/docs/4.4/utilities/text/#text-alignment) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  text-transform: uppercase;
Use [bootstrap classes for text-transform](https://getbootstrap.com/docs/4.4/utilities/text/#text-transform) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  text-transform: uppercase;
Use [bootstrap classes for text-transform](https://getbootstrap.com/docs/4.4/utilities/text/#text-transform) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  text-transform: uppercase;
Use [bootstrap classes for text-transform](https://getbootstrap.com/docs/4.4/utilities/text/#text-transform) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  text-transform: uppercase;
Use [bootstrap classes for text-transform](https://getbootstrap.com/docs/4.4/utilities/text/#text-transform) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  text-align: center;
Use [bootstrap classes for text-align](https://getbootstrap.com/docs/4.4/utilities/text/#text-alignment) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  display: block;
Use [bootstrap classes for display](https://getbootstrap.com/docs/4.4/utilities/display/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  display: inline-block;
Use [bootstrap classes for display](https://getbootstrap.com/docs/4.4/utilities/display/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  display: flex;
Use [bootstrap classes for display](https://getbootstrap.com/docs/4.4/utilities/display/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +    display: block;
Use [bootstrap classes for display](https://getbootstrap.com/docs/4.4/utilities/display/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  display: block;
Use [bootstrap classes for display](https://getbootstrap.com/docs/4.4/utilities/display/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  position: relative;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  position: absolute;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  position: absolute;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  position: absolute;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  position: relative;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  position: relative;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +    position: sticky;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +    position: sticky;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  position: relative;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  position: relative;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-01 17:14 UTC, euqueme commented on css/style.css
> +  position: relative;
Use [bootstrap classes for position](https://getbootstrap.com/docs/4.4/utilities/position/) directly in your HTML file

2020-02-02 02:43 UTC, javierbotero commented on css/style.css
> +    position: sticky;
Hello @euqueme, first of all, thanks for your review, specifically for this point I decided to let the sticky in my css due to they are not supported to be responsive using bootstrap classes 

> Quick positioning classes are available, though they are not responsive.> 

you can find the documentation here:  

`https://getbootstrap.com/docs/4.4/utilities/position/`

2020-02-02 03:54 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

# Hii @javierbotero :wave: 

### Thank you for doing all the changes you are a true MVP! :raised_hands:  I have one last but important change you still have to do:

- [ ] Fix the social media icons in the footer the images are broken

![image](https://user-images.githubusercontent.com/52209067/73602607-9b0e9580-453c-11ea-9b9a-4cec2e97472e.png)

that is it! 

### I'm trusting you do this change :handshake: and after merge it to the master do not request for a code review again

Happy Coding! :woman_technologist: 

PROJECT_STATUS: APPROVED :green_apple:

2020-02-02 03:54 UTC, euqueme commented on css/style.css
> +    position: sticky;
I agree, thank you for your comment :1st_place_medal:

2020-02-02 14:49 UTC, merged